// <auto-generated />
using System;
using Demography.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Demography.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Demography.Domain.Age", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgeValue")
                        .HasColumnType("integer")
                        .HasColumnName("age_value");

                    b.Property<Guid>("DemographyDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("demography_data_id");

                    b.Property<int>("MenQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("men_quantity");

                    b.Property<int>("WomenQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("women_quantity");

                    b.HasKey("Id");

                    b.HasIndex("DemographyDataId");

                    b.ToTable("age");
                });

            modelBuilder.Entity("Demography.Domain.DemographyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("demography_data");
                });

            modelBuilder.Entity("Demography.Domain.Density", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AreaSize")
                        .HasColumnType("double precision")
                        .HasColumnName("area_size");

                    b.Property<Guid>("DemographyDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("demography_data_id");

                    b.Property<double>("PopulationDensity")
                        .HasColumnType("double precision")
                        .HasColumnName("population_density");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("integer")
                        .HasColumnName("population_size");

                    b.HasKey("Id");

                    b.HasIndex("DemographyDataId");

                    b.ToTable("density");
                });

            modelBuilder.Entity("Demography.Domain.Ethnos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DemographyDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("demography_data_id");

                    b.Property<int>("MenQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("men_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("WomenQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("women_quantity");

                    b.HasKey("Id");

                    b.ToTable("ethnos");
                });

            modelBuilder.Entity("Demography.Domain.Migration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DemographyDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("demography_data_id");

                    b.Property<int>("EmigrantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("emigrants_count");

                    b.Property<int>("MigrantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("migrants_count");

                    b.Property<int>("MigrationRatio")
                        .HasColumnType("integer")
                        .HasColumnName("migration_ratio");

                    b.HasKey("Id");

                    b.HasIndex("DemographyDataId");

                    b.ToTable("migration");
                });

            modelBuilder.Entity("Demography.Domain.NaturalGrowth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BithRate")
                        .HasColumnType("integer")
                        .HasColumnName("bith_rate");

                    b.Property<Guid>("DemographyDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("demography_data_id");

                    b.Property<int>("MortalityRate")
                        .HasColumnType("integer")
                        .HasColumnName("mortality_rate");

                    b.HasKey("Id");

                    b.HasIndex("DemographyDataId");

                    b.ToTable("natural_growth");
                });

            modelBuilder.Entity("Demography.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("region");
                });

            modelBuilder.Entity("DemographyDataEthnos", b =>
                {
                    b.Property<Guid>("DemographyDatumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EthnicGroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DemographyDatumId", "EthnicGroupsId");

                    b.HasIndex("EthnicGroupsId");

                    b.ToTable("DemographyDataEthnos");
                });

            modelBuilder.Entity("Demography.Domain.Age", b =>
                {
                    b.HasOne("Demography.Domain.DemographyData", "DemographyData")
                        .WithMany("AgeGroups")
                        .HasForeignKey("DemographyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemographyData");
                });

            modelBuilder.Entity("Demography.Domain.DemographyData", b =>
                {
                    b.HasOne("Demography.Domain.Region", "Region")
                        .WithMany("DemographyDatum")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Demography.Domain.Density", b =>
                {
                    b.HasOne("Demography.Domain.DemographyData", "DemographyData")
                        .WithMany("DensityGroups")
                        .HasForeignKey("DemographyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemographyData");
                });

            modelBuilder.Entity("Demography.Domain.Migration", b =>
                {
                    b.HasOne("Demography.Domain.DemographyData", "DemographyData")
                        .WithMany("Migrations")
                        .HasForeignKey("DemographyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemographyData");
                });

            modelBuilder.Entity("Demography.Domain.NaturalGrowth", b =>
                {
                    b.HasOne("Demography.Domain.DemographyData", "DemographyData")
                        .WithMany("NaturalGrowthGroups")
                        .HasForeignKey("DemographyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemographyData");
                });

            modelBuilder.Entity("DemographyDataEthnos", b =>
                {
                    b.HasOne("Demography.Domain.DemographyData", null)
                        .WithMany()
                        .HasForeignKey("DemographyDatumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demography.Domain.Ethnos", null)
                        .WithMany()
                        .HasForeignKey("EthnicGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demography.Domain.DemographyData", b =>
                {
                    b.Navigation("AgeGroups");

                    b.Navigation("DensityGroups");

                    b.Navigation("Migrations");

                    b.Navigation("NaturalGrowthGroups");
                });

            modelBuilder.Entity("Demography.Domain.Region", b =>
                {
                    b.Navigation("DemographyDatum");
                });
#pragma warning restore 612, 618
        }
    }
}
